// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: checkout_session.sql

package sqlc

import (
	"context"
)

const deleteCheckOutSession = `-- name: DeleteCheckOutSession :exec
DELETE FROM checkout_sessions WHERE id = $1
`

func (q *Queries) DeleteCheckOutSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCheckOutSession, id)
	return err
}
