// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: invoice.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :exec
INSERT INTO invoices (
    id,
    customer_id,
    subscription_id,
    status,
    currency,
    amount_due,
    amount_paid,
    amount_remaining,
    due_date,
    paid_at
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9,$10
         )
`

type CreateInvoiceParams struct {
	ID              string             `json:"id"`
	CustomerID      string             `json:"customerId"`
	SubscriptionID  *string            `json:"subscriptionId"`
	Status          InvoiceStatus      `json:"status"`
	Currency        Currency           `json:"currency"`
	AmountDue       float64            `json:"amountDue"`
	AmountPaid      float64            `json:"amountPaid"`
	AmountRemaining float64            `json:"amountRemaining"`
	DueDate         pgtype.Timestamptz `json:"dueDate"`
	PaidAt          pgtype.Timestamptz `json:"paidAt"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) error {
	_, err := q.db.Exec(ctx, createInvoice,
		arg.ID,
		arg.CustomerID,
		arg.SubscriptionID,
		arg.Status,
		arg.Currency,
		arg.AmountDue,
		arg.AmountPaid,
		arg.AmountRemaining,
		arg.DueDate,
		arg.PaidAt,
	)
	return err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoices WHERE id = $1
`

func (q *Queries) DeleteInvoice(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteInvoice, id)
	return err
}

const getInvoice = `-- name: GetInvoice :one

SELECT id, customer_id, subscription_id, status, currency, amount_due, amount_paid, amount_remaining, due_date, paid_at, created_at, updated_at
FROM invoices
WHERE id = $1 LIMIT 1
`

// RETURNING id, customer_id, subscription_id, status, currency, amount_due, amount_paid, amount_remaining, due_date, paid_at, stripe_id, created_at, updated_at;
func (q *Queries) GetInvoice(ctx context.Context, id string) (*Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.Status,
		&i.Currency,
		&i.AmountDue,
		&i.AmountPaid,
		&i.AmountRemaining,
		&i.DueDate,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, customer_id, subscription_id, status, currency, amount_due, amount_paid, amount_remaining, due_date, paid_at, created_at, updated_at
FROM invoices
WHERE id = $1
`

func (q *Queries) ListInvoices(ctx context.Context, id string) ([]*Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoices, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.SubscriptionID,
			&i.Status,
			&i.Currency,
			&i.AmountDue,
			&i.AmountPaid,
			&i.AmountRemaining,
			&i.DueDate,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByCustomerID = `-- name: ListInvoicesByCustomerID :many

SELECT id, customer_id, subscription_id, status, currency, amount_due, amount_paid, amount_remaining, due_date, paid_at, created_at, updated_at
FROM invoices
WHERE customer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListInvoicesByCustomerIDParams struct {
	CustomerID string `json:"customerId"`
	Limit      int64  `json:"limit"`
	Offset     int64  `json:"offset"`
}

// RETURNING id, customer_id, subscription_id, status, currency, amount_due, amount_paid, amount_remaining, due_date, paid_at, stripe_id, created_at, updated_at;
func (q *Queries) ListInvoicesByCustomerID(ctx context.Context, arg ListInvoicesByCustomerIDParams) ([]*Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByCustomerID, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.SubscriptionID,
			&i.Status,
			&i.Currency,
			&i.AmountDue,
			&i.AmountPaid,
			&i.AmountRemaining,
			&i.DueDate,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoice = `-- name: UpdateInvoice :exec
UPDATE invoices
SET status = $2,
    amount_paid = $3,
    amount_remaining = $4,
    paid_at = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdateInvoiceParams struct {
	ID              string             `json:"id"`
	Status          InvoiceStatus      `json:"status"`
	AmountPaid      float64            `json:"amountPaid"`
	AmountRemaining float64            `json:"amountRemaining"`
	PaidAt          pgtype.Timestamptz `json:"paidAt"`
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) error {
	_, err := q.db.Exec(ctx, updateInvoice,
		arg.ID,
		arg.Status,
		arg.AmountPaid,
		arg.AmountRemaining,
		arg.PaidAt,
	)
	return err
}

const upsertInvoice = `-- name: UpsertInvoice :exec
INSERT INTO invoices (
    id, customer_id, subscription_id, status, currency, amount_due, amount_paid,
    amount_remaining, due_date, paid_at
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
         )
ON CONFLICT (id) DO UPDATE SET
                                      customer_id = EXCLUDED.customer_id,
                                      subscription_id = EXCLUDED.subscription_id,
                                      status = EXCLUDED.status,
                                      currency = EXCLUDED.currency,
                                      amount_due = EXCLUDED.amount_due,
                                      amount_paid = EXCLUDED.amount_paid,
                                      amount_remaining = EXCLUDED.amount_remaining,
                                      due_date = EXCLUDED.due_date,
                                      paid_at = EXCLUDED.paid_at,
                                      updated_at = NOW()
`

type UpsertInvoiceParams struct {
	ID              string             `json:"id"`
	CustomerID      string             `json:"customerId"`
	SubscriptionID  *string            `json:"subscriptionId"`
	Status          InvoiceStatus      `json:"status"`
	Currency        Currency           `json:"currency"`
	AmountDue       float64            `json:"amountDue"`
	AmountPaid      float64            `json:"amountPaid"`
	AmountRemaining float64            `json:"amountRemaining"`
	DueDate         pgtype.Timestamptz `json:"dueDate"`
	PaidAt          pgtype.Timestamptz `json:"paidAt"`
}

func (q *Queries) UpsertInvoice(ctx context.Context, arg UpsertInvoiceParams) error {
	_, err := q.db.Exec(ctx, upsertInvoice,
		arg.ID,
		arg.CustomerID,
		arg.SubscriptionID,
		arg.Status,
		arg.Currency,
		arg.AmountDue,
		arg.AmountPaid,
		arg.AmountRemaining,
		arg.DueDate,
		arg.PaidAt,
	)
	return err
}
