// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payment_link.sql

package sqlc

import (
	"context"
)

const deletePaymentLink = `-- name: DeletePaymentLink :exec
DELETE FROM payment_links WHERE id = $1
`

func (q *Queries) DeletePaymentLink(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePaymentLink, id)
	return err
}
