// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: price.sql

package sqlc

import (
	"context"
)

const createPrice = `-- name: CreatePrice :exec
INSERT INTO prices (
    product_id,
    type,
    currency,
    unit_amount,
    recurring_interval,
    recurring_interval_count,
    trial_period_days,
    active,
    stripe_id
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9
         )
`

type CreatePriceParams struct {
	ProductID              uint64           `json:"productId"`
	Type                   PriceType        `json:"type"`
	Currency               Currency         `json:"currency"`
	UnitAmount             float64          `json:"unitAmount"`
	RecurringInterval      NullIntervalType `json:"recurringInterval"`
	RecurringIntervalCount int32            `json:"recurringIntervalCount"`
	TrialPeriodDays        int32            `json:"trialPeriodDays"`
	Active                 bool             `json:"active"`
	StripeID               string           `json:"stripeId"`
}

func (q *Queries) CreatePrice(ctx context.Context, arg CreatePriceParams) error {
	_, err := q.db.Exec(ctx, createPrice,
		arg.ProductID,
		arg.Type,
		arg.Currency,
		arg.UnitAmount,
		arg.RecurringInterval,
		arg.RecurringIntervalCount,
		arg.TrialPeriodDays,
		arg.Active,
		arg.StripeID,
	)
	return err
}

const deletePrice = `-- name: DeletePrice :exec

DELETE FROM prices WHERE id = $1
`

// RETURNING id, product_id, type, currency, unit_amount, recurring_interval, recurring_interval_count, trial_period_days, active, stripe_id, created_at, updated_at;
func (q *Queries) DeletePrice(ctx context.Context, id uint64) error {
	_, err := q.db.Exec(ctx, deletePrice, id)
	return err
}

const getPrice = `-- name: GetPrice :one

SELECT id, product_id, type, currency, unit_amount, recurring_interval, recurring_interval_count, trial_period_days, active, stripe_id, created_at, updated_at
FROM prices
WHERE id = $1 LIMIT 1
`

// RETURNING id, product_id, type, currency, unit_amount, recurring_interval, recurring_interval_count, trial_period_days, active, stripe_id, created_at, updated_at;
func (q *Queries) GetPrice(ctx context.Context, id uint64) (*Price, error) {
	row := q.db.QueryRow(ctx, getPrice, id)
	var i Price
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Type,
		&i.Currency,
		&i.UnitAmount,
		&i.RecurringInterval,
		&i.RecurringIntervalCount,
		&i.TrialPeriodDays,
		&i.Active,
		&i.StripeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listPrices = `-- name: ListPrices :many
SELECT id, product_id, type, currency, unit_amount, recurring_interval, recurring_interval_count, trial_period_days, active, stripe_id, created_at, updated_at
FROM prices
WHERE product_id = $1 AND active = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListPricesParams struct {
	ProductID uint64 `json:"productId"`
	Active    bool   `json:"active"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) ListPrices(ctx context.Context, arg ListPricesParams) ([]*Price, error) {
	rows, err := q.db.Query(ctx, listPrices,
		arg.ProductID,
		arg.Active,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Price{}
	for rows.Next() {
		var i Price
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Type,
			&i.Currency,
			&i.UnitAmount,
			&i.RecurringInterval,
			&i.RecurringIntervalCount,
			&i.TrialPeriodDays,
			&i.Active,
			&i.StripeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrice = `-- name: UpdatePrice :exec
UPDATE prices
SET product_id = $2,
    type = $3,
    currency = $4,
    unit_amount = $5,
    recurring_interval = $6,
    recurring_interval_count = $7,
    trial_period_days = $8,
    active = $9,
    stripe_id = $10,
    updated_at = NOW()
WHERE id = $1
`

type UpdatePriceParams struct {
	ID                     uint64           `json:"id"`
	ProductID              uint64           `json:"productId"`
	Type                   PriceType        `json:"type"`
	Currency               Currency         `json:"currency"`
	UnitAmount             float64          `json:"unitAmount"`
	RecurringInterval      NullIntervalType `json:"recurringInterval"`
	RecurringIntervalCount int32            `json:"recurringIntervalCount"`
	TrialPeriodDays        int32            `json:"trialPeriodDays"`
	Active                 bool             `json:"active"`
	StripeID               string           `json:"stripeId"`
}

func (q *Queries) UpdatePrice(ctx context.Context, arg UpdatePriceParams) error {
	_, err := q.db.Exec(ctx, updatePrice,
		arg.ID,
		arg.ProductID,
		arg.Type,
		arg.Currency,
		arg.UnitAmount,
		arg.RecurringInterval,
		arg.RecurringIntervalCount,
		arg.TrialPeriodDays,
		arg.Active,
		arg.StripeID,
	)
	return err
}
