// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reviews.sql

package sqlc

import (
	"context"
)

const deleteReviews = `-- name: DeleteReviews :exec
DELETE FROM reviews WHERE id = $1
`

func (q *Queries) DeleteReviews(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteReviews, id)
	return err
}
