// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tax_rate.sql

package sqlc

import (
	"context"
)

const deleteTaxRate = `-- name: DeleteTaxRate :exec
DELETE FROM tax_rates WHERE id = $1
`

func (q *Queries) DeleteTaxRate(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTaxRate, id)
	return err
}
