package payment

const (
	NatsSubjectSingleAll      string = ".*"
	NatsSubjectAll            string = ".>"
	NatsSubjectEventProcessed string = "stripe.event.processed"

	NatsSubjectProcessed string = ".processed"
	NatsSubjectCreated   string = ".created"
	NatsSubjectUpdated   string = ".updated"
	NatsSubjectDeleted   string = ".deleted"
	NatsSubjectSucceeded string = ".succeeded"
	NatsSubjectFailed    string = ".failed"
	NatsSubjectRefunded  string = ".refunded"
	NatsSubjectCaptured  string = ".captured"
	NatsSubjectExpired   string = ".expired"
	NatsSubjectSession   string = ".session"

	NatsSubjectCustomer      string = ".customer"
	NatsSubjectSubscription  string = ".subscription"
	NatsSubjectInvoice       string = ".invoice"
	NatsSubjectPaymentIntent string = ".payment_intent"
	NatsSubjectCharge        string = ".charge"
	NatsSubjectDispute       string = ".dispute"
	NatsSubjectProduct       string = ".product"
	NatsSubjectPrice         string = ".price"
	NatsSubjectPaymentMethod string = ".payment_method"
	NatsSubjectCoupon        string = ".coupon"
	NatsSubjectDiscount      string = ".discount"
	NatsSubjectCheckout      string = ".checkout"
	NatsSubjectRefund        string = ".refund"
	NatsSubjectPromotionCode string = ".promotion_code"
	NatsSubjectQuote         string = ".quote"
	NatsSubjectPaymentLink   string = ".payment_link"
	NatsSubjectTaxRate       string = ".tax_rate"
	NatsSubjectReview        string = ".review"
)
