DROP INDEX IF EXISTS idx_customers_user_id;
DROP INDEX IF EXISTS idx_customers_id;
DROP INDEX IF EXISTS idx_products_id;
DROP INDEX IF EXISTS idx_prices_id;
DROP INDEX IF EXISTS idx_subscriptions_id;
DROP INDEX IF EXISTS idx_invoices_id;
DROP INDEX IF EXISTS idx_payment_methods_id;
DROP INDEX IF EXISTS idx_payment_intents_id;
DROP INDEX IF EXISTS idx_invoice_items_invoice_id;
DROP INDEX IF EXISTS idx_refunds_payment_intent_id;
DROP INDEX IF EXISTS idx_refunds_id;
DROP INDEX IF EXISTS idx_events_processed;
DROP INDEX IF EXISTS idx_disputes_id;
DROP INDEX IF EXISTS idx_disputes_charge_id;
DROP INDEX IF EXISTS idx_coupons_id;
DROP INDEX IF EXISTS idx_discounts_customer_id;
DROP INDEX IF EXISTS idx_discounts_coupon_id;
DROP INDEX IF EXISTS idx_promotion_codes_coupon_id;
DROP INDEX IF EXISTS idx_promotion_codes_customer_id;
DROP INDEX IF EXISTS idx_checkout_sessions_customer_id;
DROP INDEX IF EXISTS idx_checkout_sessions_payment_intent_id;
DROP INDEX IF EXISTS idx_quotes_customer_id;
DROP INDEX IF EXISTS idx_reviews_payment_intent_id;


DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS prices CASCADE;
DROP TABLE IF EXISTS subscriptions CASCADE;
DROP TABLE IF EXISTS invoices CASCADE;
DROP TABLE IF EXISTS invoice_items CASCADE;
DROP TABLE IF EXISTS payment_methods CASCADE;
DROP TABLE IF EXISTS payment_intents CASCADE;
DROP TABLE IF EXISTS charges CASCADE;
DROP TABLE IF EXISTS refunds CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS disputes CASCADE;
DROP TABLE IF EXISTS coupons CASCADE;
DROP TABLE IF EXISTS discounts CASCADE;
DROP TABLE IF EXISTS promotion_codes CASCADE;
DROP TABLE IF EXISTS checkout_sessions CASCADE;
DROP TABLE IF EXISTS quotes CASCADE;
DROP TABLE IF EXISTS payment_links CASCADE;
DROP TABLE IF EXISTS tax_rates CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
